# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QQuakeDialog
                                 A QGIS plugin
 QQuake plugin to download seismologic data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-11-20
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Faunalia
        email                : matteo.ghetta@faunalia.eu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt.QtWidgets import (
    QDialogButtonBox,
    QDialog
)

from qgis.core import (
    QgsProject,
    QgsRectangle,
    QgsCoordinateReferenceSystem,
    QgsSettings
)
from qgis.gui import QgsGui

from qquake.qquake_defs import (
    fdsn_events_capabilities,
    MAX_LON_LAT
)

from qquake.fetcher import Fetcher

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'qquake_dialog_base.ui'))


class QQuakeDialog(QDialog, FORM_CLASS):

    def __init__(self, iface, parent=None):
        """Constructor."""
        super().__init__(parent)

        self.setupUi(self)

        self.url_text_browser.viewport().setAutoFillBackground(False)
        self.button_box.button(QDialogButtonBox.Ok).setText(self.tr('Fetch Data'))

        self.iface = iface

        # QgsExtentGroupBox utilities to se tup in the init
        self.mExtentGroupBox.setMapCanvas(self.iface.mapCanvas())
        self.mExtentGroupBox.setCurrentExtent(self.iface.mapCanvas().extent(),
                                              self.iface.mapCanvas().mapSettings().destinationCrs())
        self.mExtentGroupBox.setOriginalExtent(QgsRectangle(*MAX_LON_LAT), QgsCoordinateReferenceSystem('EPSG:4326'))
        self.mExtentGroupBox.setOutputCrs(QgsCoordinateReferenceSystem('EPSG:4326'))

        # connect the date changing to the refreshing function
        self.fdsn_event_start_date.dateChanged.connect(self._refresh_date)

        # fill the FDSN combobox with the dictionary keys
        self.fdsn_event_ws_combobox.addItems(fdsn_events_capabilities.keys())

        # connect to refreshing function to refresh the UI depending on the WS
        self.refreshWidgets()

        # change the UI parameter according to the web service chosen
        self.fdsn_event_ws_combobox.currentIndexChanged.connect(self.refreshWidgets)

        self.fdsn_event_ws_combobox.currentIndexChanged.connect(self._refresh_url)
        self.fdsn_event_start_date.dateChanged.connect(self._refresh_url)
        self.fdsn_event_end_date.dateChanged.connect(self._refresh_url)
        self.fdsn_event_min_magnitude.valueChanged.connect(self._refresh_url)
        self.fdsn_event_max_magnitude.valueChanged.connect(self._refresh_url)
        self.mExtentGroupBox.extentChanged.connect(self._refresh_url)
        self.mExtentGroupBox.toggled.connect(self._refresh_url)

        self.button_box.accepted.connect(self._getEventList)

        self.fetcher = None

        QgsGui.enableAutoGeometryRestore(self)

        self._restore_settings()
        self._refresh_url()

    def _save_settings(self):
        s = QgsSettings()
        s.setValue('/plugins/qquake/last_event_service', self.fdsn_event_ws_combobox.currentText())
        s.setValue('/plugins/qquake/last_event_start_date', self.fdsn_event_start_date.dateTime())
        s.setValue('/plugins/qquake/last_event_end_date', self.fdsn_event_end_date.dateTime())
        s.setValue('/plugins/qquake/last_event_min_magnitude',self.fdsn_event_min_magnitude.value())
        s.setValue('/plugins/qquake/last_event_max_magnitude', self.fdsn_event_max_magnitude.value())
        s.setValue('/plugins/qquake/last_event_extent', '{}|{}|{}|{}'.format(self.mExtentGroupBox.outputExtent().xMinimum(),
                                                                             self.mExtentGroupBox.outputExtent().yMinimum(),
                                                                             self.mExtentGroupBox.outputExtent().xMaximum(),
                                                                             self.mExtentGroupBox.outputExtent().yMaximum()))
        s.setValue('/plugins/qquake/last_event_extent_enabled', self.mExtentGroupBox.isChecked())

    def _restore_settings(self):
        s = QgsSettings()
        last_service = s.value('/plugins/qquake/last_event_service')
        if last_service is not None:
            self.fdsn_event_ws_combobox.setCurrentIndex(self.fdsn_event_ws_combobox.findText(last_service))
        last_event_start_date = s.value('/plugins/qquake/last_event_start_date')
        if last_event_start_date is not None:
            self.fdsn_event_start_date.setDateTime(last_event_start_date)
        last_event_end_date = s.value('/plugins/qquake/last_event_end_date')
        if last_event_end_date is not None:
            self.fdsn_event_end_date.setDateTime(last_event_end_date)
        last_event_min_magnitude = s.value('/plugins/qquake/last_event_min_magnitude')
        if last_event_min_magnitude is not None:
            self.fdsn_event_min_magnitude.setValue(last_event_min_magnitude)
        last_event_max_magnitude = s.value('/plugins/qquake/last_event_max_magnitude')
        if last_event_max_magnitude is not None:
            self.fdsn_event_max_magnitude.setValue(last_event_max_magnitude)
        last_event_extent = s.value('/plugins/qquake/last_event_extent')
        if last_event_extent:
            parts = last_event_extent.split('|')
            if len(parts) == 4:
                r = QgsRectangle()
                try:
                    r.setXMinimum(float(parts[0]))
                    r.setYMinimum(float(parts[1]))
                    r.setXMaximum(float(parts[2]))
                    r.setYMaximum(float(parts[3]))
                    self.mExtentGroupBox.setOriginalExtent(r, QgsCoordinateReferenceSystem('EPSG:4326'))
                except:
                    pass
        last_event_extent_enabled = s.value('/plugins/qquake/last_event_extent_enabled')
        if last_event_extent_enabled is not None:
            self.mExtentGroupBox.setChecked(bool(last_event_extent_enabled))

    def _refresh_date(self):
        """
        Avoids negative date intervals by checking start_date > end_date
        """
        if self.fdsn_event_start_date.dateTime() > self.fdsn_event_end_date.dateTime():
            self.fdsn_event_end_date.setDate(self.fdsn_event_start_date.date())

    def get_fetcher(self):
        """
        Returns a quake fetcher corresponding to the current dialog settings
        """
        return Fetcher(event_service=self.fdsn_event_ws_combobox.currentText(),
                       event_start_date=self.fdsn_event_start_date.dateTime(),
                       event_end_date=self.fdsn_event_end_date.dateTime(),
                       event_min_magnitude=self.fdsn_event_min_magnitude.value(),
                       event_max_magnitude=self.fdsn_event_max_magnitude.value(),
                       extent=self.mExtentGroupBox.outputExtent() if self.mExtentGroupBox.isChecked() else None)

    def _refresh_url(self):
        fetcher = self.get_fetcher()
        self.url_text_browser.setText('<a href="{0}">{0}</a>'.format(fetcher.generate_url()))

    def refreshWidgets(self):
        """
        Refreshing the FDSN-Event UI depending on the WS chosen
        """

        # set DateTime Widget START according to the combobox choice
        self.fdsn_event_start_date.setMinimumDate(
            fdsn_events_capabilities[self.fdsn_event_ws_combobox.currentText()]['mindate']
        )
        self.fdsn_event_start_date.setMaximumDate(
            fdsn_events_capabilities[self.fdsn_event_ws_combobox.currentText()]['maxdate']
        )
        self.fdsn_event_start_date.setDate(
            fdsn_events_capabilities[self.fdsn_event_ws_combobox.currentText()]['defaultdate']
        )

        # set DateTime Widget END according to the combobox choice
        self.fdsn_event_end_date.setMinimumDate(
            fdsn_events_capabilities[self.fdsn_event_ws_combobox.currentText()]['mindate']
        )
        self.fdsn_event_end_date.setMaximumDate(
            fdsn_events_capabilities[self.fdsn_event_ws_combobox.currentText()]['maxdate']
        )
        # just make a week difference from START date
        self.fdsn_event_end_date.setDate(
            fdsn_events_capabilities[self.fdsn_event_ws_combobox.currentText()]['defaultdate'].addDays(-7)
        )

    def _getEventList(self):
        """
        read the event URL and convert the response in a list
        """
        if self.fetcher:
            # TODO - cancel current request
            return

        self._save_settings()

        self.fetcher = self.get_fetcher()
        self.fetcher.progress.connect(self.progressBar.setValue)
        self.fetcher.finished.connect(self._fetcher_finished)
        self.button_box.button(QDialogButtonBox.Ok).setText(self.tr('Fetching'))
        self.button_box.button(QDialogButtonBox.Ok).setEnabled(False)

        self.fetcher.fetch_data()

    def _fetcher_finished(self):
        self.progressBar.reset()
        self.button_box.button(QDialogButtonBox.Ok).setText(self.tr('Fetch Data'))
        self.button_box.button(QDialogButtonBox.Ok).setEnabled(True)

        event_layer = self.fetcher.create_event_layer()
        origin_layer = self.fetcher.create_origin_layer()

        self.fetcher.deleteLater()
        self.fetcher = None

        QgsProject.instance().addMapLayers([event_layer, origin_layer])

