# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\giorg\AppData\Roaming\QGIS\QGIS3\profiles\qquake\python\plugins\qquake\ui\filter_parameter_widget_base.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_filter_parameter_widget_base(object):
    def setupUi(self, filter_parameter_widget_base):
        filter_parameter_widget_base.setObjectName("filter_parameter_widget_base")
        filter_parameter_widget_base.resize(561, 957)
        self.verticalLayout = QtWidgets.QVBoxLayout(filter_parameter_widget_base)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scroll_area = QtWidgets.QScrollArea(filter_parameter_widget_base)
        self.scroll_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scroll_area.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 561, 957))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.magnitude_group = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.magnitude_group.setObjectName("magnitude_group")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.magnitude_group)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.fdsn_event_min_magnitude = QtWidgets.QDoubleSpinBox(self.magnitude_group)
        self.fdsn_event_min_magnitude.setDecimals(1)
        self.fdsn_event_min_magnitude.setMinimum(-9.0)
        self.fdsn_event_min_magnitude.setMaximum(9.0)
        self.fdsn_event_min_magnitude.setSingleStep(0.5)
        self.fdsn_event_min_magnitude.setProperty("value", 4.0)
        self.fdsn_event_min_magnitude.setObjectName("fdsn_event_min_magnitude")
        self.gridLayout_7.addWidget(self.fdsn_event_min_magnitude, 0, 1, 1, 1)
        self.max_mag_check = QtWidgets.QCheckBox(self.magnitude_group)
        self.max_mag_check.setObjectName("max_mag_check")
        self.gridLayout_7.addWidget(self.max_mag_check, 1, 0, 1, 1)
        self.min_mag_check = QtWidgets.QCheckBox(self.magnitude_group)
        self.min_mag_check.setObjectName("min_mag_check")
        self.gridLayout_7.addWidget(self.min_mag_check, 0, 0, 1, 1)
        self.fdsn_event_max_magnitude = QtWidgets.QDoubleSpinBox(self.magnitude_group)
        self.fdsn_event_max_magnitude.setDecimals(1)
        self.fdsn_event_max_magnitude.setMinimum(1.0)
        self.fdsn_event_max_magnitude.setMaximum(9.0)
        self.fdsn_event_max_magnitude.setSingleStep(0.5)
        self.fdsn_event_max_magnitude.setProperty("value", 9.0)
        self.fdsn_event_max_magnitude.setObjectName("fdsn_event_max_magnitude")
        self.gridLayout_7.addWidget(self.fdsn_event_max_magnitude, 1, 1, 1, 1)
        self.gridLayout_7.setColumnStretch(0, 1)
        self.gridLayout_7.setColumnStretch(1, 2)
        self.verticalLayout_2.addWidget(self.magnitude_group)
        self.time_coverage_group = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.time_coverage_group.setObjectName("time_coverage_group")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.time_coverage_group)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.min_time_check = QtWidgets.QCheckBox(self.time_coverage_group)
        self.min_time_check.setObjectName("min_time_check")
        self.gridLayout_3.addWidget(self.min_time_check, 0, 0, 1, 1)
        self.fdsn_event_start_date = QtWidgets.QDateTimeEdit(self.time_coverage_group)
        self.fdsn_event_start_date.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(23, 59, 59), QtCore.QTime(9999, 12, 31)))
        self.fdsn_event_start_date.setCalendarPopup(True)
        self.fdsn_event_start_date.setObjectName("fdsn_event_start_date")
        self.gridLayout_3.addWidget(self.fdsn_event_start_date, 0, 1, 1, 1)
        self.fdsn_event_end_date = QtWidgets.QDateTimeEdit(self.time_coverage_group)
        self.fdsn_event_end_date.setMinimumDate(QtCore.QDate(1777, 9, 14))
        self.fdsn_event_end_date.setCalendarPopup(True)
        self.fdsn_event_end_date.setObjectName("fdsn_event_end_date")
        self.gridLayout_3.addWidget(self.fdsn_event_end_date, 1, 1, 1, 1)
        self.max_time_check = QtWidgets.QCheckBox(self.time_coverage_group)
        self.max_time_check.setObjectName("max_time_check")
        self.gridLayout_3.addWidget(self.max_time_check, 1, 0, 1, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.verticalLayout_2.addWidget(self.time_coverage_group)
        self.limit_extent_checkbox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.limit_extent_checkbox.setFlat(False)
        self.limit_extent_checkbox.setCheckable(True)
        self.limit_extent_checkbox.setChecked(False)
        self.limit_extent_checkbox.setObjectName("limit_extent_checkbox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.limit_extent_checkbox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.radius_max_spinbox = QtWidgets.QDoubleSpinBox(self.limit_extent_checkbox)
        self.radius_max_spinbox.setDecimals(3)
        self.radius_max_spinbox.setMinimum(0.0)
        self.radius_max_spinbox.setMaximum(999999999.0)
        self.radius_max_spinbox.setObjectName("radius_max_spinbox")
        self.gridLayout_6.addWidget(self.radius_max_spinbox, 12, 3, 1, 1)
        self.label_circ_radius = QtWidgets.QLabel(self.limit_extent_checkbox)
        self.label_circ_radius.setObjectName("label_circ_radius")
        self.gridLayout_6.addWidget(self.label_circ_radius, 11, 1, 1, 1)
        self.lat_max_checkbox = QtWidgets.QCheckBox(self.limit_extent_checkbox)
        self.lat_max_checkbox.setObjectName("lat_max_checkbox")
        self.gridLayout_6.addWidget(self.lat_max_checkbox, 3, 2, 1, 1)
        self.radio_rectangular_area = QtWidgets.QRadioButton(self.limit_extent_checkbox)
        self.radio_rectangular_area.setChecked(True)
        self.radio_rectangular_area.setObjectName("radio_rectangular_area")
        self.gridLayout_6.addWidget(self.radio_rectangular_area, 2, 0, 1, 1)
        self.label_rect_long = QtWidgets.QLabel(self.limit_extent_checkbox)
        self.label_rect_long.setObjectName("label_rect_long")
        self.gridLayout_6.addWidget(self.label_rect_long, 4, 1, 1, 1)
        self.lat_max_spinbox = QtWidgets.QDoubleSpinBox(self.limit_extent_checkbox)
        self.lat_max_spinbox.setDecimals(3)
        self.lat_max_spinbox.setMinimum(-90.0)
        self.lat_max_spinbox.setMaximum(90.0)
        self.lat_max_spinbox.setObjectName("lat_max_spinbox")
        self.gridLayout_6.addWidget(self.lat_max_spinbox, 3, 3, 1, 1)
        self.long_max_checkbox = QtWidgets.QCheckBox(self.limit_extent_checkbox)
        self.long_max_checkbox.setObjectName("long_max_checkbox")
        self.gridLayout_6.addWidget(self.long_max_checkbox, 5, 2, 1, 1)
        self.circle_center_draw_on_map = QtWidgets.QPushButton(self.limit_extent_checkbox)
        self.circle_center_draw_on_map.setObjectName("circle_center_draw_on_map")
        self.gridLayout_6.addWidget(self.circle_center_draw_on_map, 10, 2, 1, 2)
        self.lat_min_spinbox = QtWidgets.QDoubleSpinBox(self.limit_extent_checkbox)
        self.lat_min_spinbox.setDecimals(3)
        self.lat_min_spinbox.setMinimum(-90.0)
        self.lat_min_spinbox.setMaximum(90.0)
        self.lat_min_spinbox.setObjectName("lat_min_spinbox")
        self.gridLayout_6.addWidget(self.lat_min_spinbox, 2, 3, 1, 1)
        self.long_max_spinbox = QtWidgets.QDoubleSpinBox(self.limit_extent_checkbox)
        self.long_max_spinbox.setDecimals(3)
        self.long_max_spinbox.setMinimum(-180.0)
        self.long_max_spinbox.setMaximum(180.0)
        self.long_max_spinbox.setSingleStep(1.0)
        self.long_max_spinbox.setObjectName("long_max_spinbox")
        self.gridLayout_6.addWidget(self.long_max_spinbox, 5, 3, 1, 1)
        self.radius_unit_combobox = QtWidgets.QComboBox(self.limit_extent_checkbox)
        self.radius_unit_combobox.setObjectName("radius_unit_combobox")
        self.gridLayout_6.addWidget(self.radius_unit_combobox, 13, 2, 1, 2)
        self.radius_min_spinbox = QtWidgets.QDoubleSpinBox(self.limit_extent_checkbox)
        self.radius_min_spinbox.setDecimals(3)
        self.radius_min_spinbox.setMinimum(0.0)
        self.radius_min_spinbox.setMaximum(999999999.0)
        self.radius_min_spinbox.setObjectName("radius_min_spinbox")
        self.gridLayout_6.addWidget(self.radius_min_spinbox, 11, 3, 1, 1)
        self.radius_max_checkbox = QtWidgets.QCheckBox(self.limit_extent_checkbox)
        self.radius_max_checkbox.setObjectName("radius_max_checkbox")
        self.gridLayout_6.addWidget(self.radius_max_checkbox, 12, 2, 1, 1)
        self.label_circ_lat = QtWidgets.QLabel(self.limit_extent_checkbox)
        self.label_circ_lat.setObjectName("label_circ_lat")
        self.gridLayout_6.addWidget(self.label_circ_lat, 8, 2, 1, 1)
        self.label_circ_long = QtWidgets.QLabel(self.limit_extent_checkbox)
        self.label_circ_long.setObjectName("label_circ_long")
        self.gridLayout_6.addWidget(self.label_circ_long, 9, 2, 1, 1)
        self.circular_long_spinbox = QtWidgets.QDoubleSpinBox(self.limit_extent_checkbox)
        self.circular_long_spinbox.setDecimals(3)
        self.circular_long_spinbox.setMinimum(-180.0)
        self.circular_long_spinbox.setMaximum(180.0)
        self.circular_long_spinbox.setSingleStep(1.0)
        self.circular_long_spinbox.setObjectName("circular_long_spinbox")
        self.gridLayout_6.addWidget(self.circular_long_spinbox, 9, 3, 1, 1)
        self.radio_circular_area = QtWidgets.QRadioButton(self.limit_extent_checkbox)
        self.radio_circular_area.setObjectName("radio_circular_area")
        self.gridLayout_6.addWidget(self.radio_circular_area, 8, 0, 1, 1)
        self.label_circ_center = QtWidgets.QLabel(self.limit_extent_checkbox)
        self.label_circ_center.setObjectName("label_circ_center")
        self.gridLayout_6.addWidget(self.label_circ_center, 8, 1, 1, 1)
        self.long_min_checkbox = QtWidgets.QCheckBox(self.limit_extent_checkbox)
        self.long_min_checkbox.setObjectName("long_min_checkbox")
        self.gridLayout_6.addWidget(self.long_min_checkbox, 4, 2, 1, 1)
        self.rect_extent_draw_on_map = QtWidgets.QPushButton(self.limit_extent_checkbox)
        self.rect_extent_draw_on_map.setObjectName("rect_extent_draw_on_map")
        self.gridLayout_6.addWidget(self.rect_extent_draw_on_map, 6, 2, 1, 2)
        self.circular_lat_spinbox = QtWidgets.QDoubleSpinBox(self.limit_extent_checkbox)
        self.circular_lat_spinbox.setDecimals(3)
        self.circular_lat_spinbox.setMinimum(-90.0)
        self.circular_lat_spinbox.setMaximum(90.0)
        self.circular_lat_spinbox.setObjectName("circular_lat_spinbox")
        self.gridLayout_6.addWidget(self.circular_lat_spinbox, 8, 3, 1, 1)
        self.label_rect_lat = QtWidgets.QLabel(self.limit_extent_checkbox)
        self.label_rect_lat.setObjectName("label_rect_lat")
        self.gridLayout_6.addWidget(self.label_rect_lat, 2, 1, 1, 1)
        self.radius_min_checkbox = QtWidgets.QCheckBox(self.limit_extent_checkbox)
        self.radius_min_checkbox.setObjectName("radius_min_checkbox")
        self.gridLayout_6.addWidget(self.radius_min_checkbox, 11, 2, 1, 1)
        self.long_min_spinbox = QtWidgets.QDoubleSpinBox(self.limit_extent_checkbox)
        self.long_min_spinbox.setDecimals(3)
        self.long_min_spinbox.setMinimum(-180.0)
        self.long_min_spinbox.setMaximum(180.0)
        self.long_min_spinbox.setSingleStep(1.0)
        self.long_min_spinbox.setObjectName("long_min_spinbox")
        self.gridLayout_6.addWidget(self.long_min_spinbox, 4, 3, 1, 1)
        self.lat_min_checkbox = QtWidgets.QCheckBox(self.limit_extent_checkbox)
        self.lat_min_checkbox.setObjectName("lat_min_checkbox")
        self.gridLayout_6.addWidget(self.lat_min_checkbox, 2, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.combo_predefined_area = QtWidgets.QComboBox(self.limit_extent_checkbox)
        self.combo_predefined_area.setObjectName("combo_predefined_area")
        self.horizontalLayout.addWidget(self.combo_predefined_area)
        self.button_customize_areas = QtWidgets.QPushButton(self.limit_extent_checkbox)
        self.button_customize_areas.setObjectName("button_customize_areas")
        self.horizontalLayout.addWidget(self.button_customize_areas)
        self.horizontalLayout.setStretch(0, 1)
        self.gridLayout_6.addLayout(self.horizontalLayout, 0, 2, 1, 2)
        self.radio_predefined_area = QtWidgets.QRadioButton(self.limit_extent_checkbox)
        self.radio_predefined_area.setObjectName("radio_predefined_area")
        self.gridLayout_6.addWidget(self.radio_predefined_area, 0, 0, 1, 2)
        self.gridLayout_6.setColumnStretch(2, 1)
        self.gridLayout_6.setColumnStretch(3, 1)
        self.verticalLayout_2.addWidget(self.limit_extent_checkbox)
        self.macroseismic_data_group = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.macroseismic_data_group.setCheckable(False)
        self.macroseismic_data_group.setChecked(False)
        self.macroseismic_data_group.setObjectName("macroseismic_data_group")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.macroseismic_data_group)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.earthquake_number_mdps_greater_check = QtWidgets.QCheckBox(self.macroseismic_data_group)
        self.earthquake_number_mdps_greater_check.setObjectName("earthquake_number_mdps_greater_check")
        self.gridLayout_2.addWidget(self.earthquake_number_mdps_greater_check, 1, 0, 1, 1)
        self.earthquake_max_intensity_greater_check = QtWidgets.QCheckBox(self.macroseismic_data_group)
        self.earthquake_max_intensity_greater_check.setObjectName("earthquake_max_intensity_greater_check")
        self.gridLayout_2.addWidget(self.earthquake_max_intensity_greater_check, 0, 0, 1, 1)
        self.earthquake_number_mdps_greater_spin = QtWidgets.QSpinBox(self.macroseismic_data_group)
        self.earthquake_number_mdps_greater_spin.setMaximum(999999)
        self.earthquake_number_mdps_greater_spin.setProperty("value", 20)
        self.earthquake_number_mdps_greater_spin.setObjectName("earthquake_number_mdps_greater_spin")
        self.gridLayout_2.addWidget(self.earthquake_number_mdps_greater_spin, 1, 1, 1, 1)
        self.earthquake_max_intensity_greater_combo = QtWidgets.QComboBox(self.macroseismic_data_group)
        self.earthquake_max_intensity_greater_combo.setObjectName("earthquake_max_intensity_greater_combo")
        self.gridLayout_2.addWidget(self.earthquake_max_intensity_greater_combo, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.verticalLayout_2.addWidget(self.macroseismic_data_group)
        self.macroseismic_data_group_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.macroseismic_data_group_2.setCheckable(False)
        self.macroseismic_data_group_2.setChecked(False)
        self.macroseismic_data_group_2.setObjectName("macroseismic_data_group_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.macroseismic_data_group_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.event_type_combo = QtWidgets.QComboBox(self.macroseismic_data_group_2)
        self.event_type_combo.setObjectName("event_type_combo")
        self.gridLayout_4.addWidget(self.event_type_combo, 0, 1, 1, 1)
        self.event_type_check = QtWidgets.QCheckBox(self.macroseismic_data_group_2)
        self.event_type_check.setObjectName("event_type_check")
        self.gridLayout_4.addWidget(self.event_type_check, 0, 0, 1, 1)
        self.events_updated_after_check = QtWidgets.QCheckBox(self.macroseismic_data_group_2)
        self.events_updated_after_check.setObjectName("events_updated_after_check")
        self.gridLayout_4.addWidget(self.events_updated_after_check, 1, 0, 1, 1)
        self.events_updated_after = QtWidgets.QDateTimeEdit(self.macroseismic_data_group_2)
        self.events_updated_after.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(9999, 12, 31), QtCore.QTime(23, 59, 59)))
        self.events_updated_after.setCalendarPopup(True)
        self.events_updated_after.setObjectName("events_updated_after")
        self.gridLayout_4.addWidget(self.events_updated_after, 1, 1, 1, 1)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.verticalLayout_2.addWidget(self.macroseismic_data_group_2)
        self.output_options_widget = OutputOptionsWidget(self.scrollAreaWidgetContents)
        self.output_options_widget.setObjectName("output_options_widget")
        self.verticalLayout_2.addWidget(self.output_options_widget)
        self.output_table_options_widget = OutputTableOptionsWidget(self.scrollAreaWidgetContents)
        self.output_table_options_widget.setObjectName("output_table_options_widget")
        self.verticalLayout_2.addWidget(self.output_table_options_widget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scroll_area)

        self.retranslateUi(filter_parameter_widget_base)
        QtCore.QMetaObject.connectSlotsByName(filter_parameter_widget_base)

    def retranslateUi(self, filter_parameter_widget_base):
        _translate = QtCore.QCoreApplication.translate
        filter_parameter_widget_base.setWindowTitle(_translate("filter_parameter_widget_base", "Form"))
        self.magnitude_group.setTitle(_translate("filter_parameter_widget_base", "Magnitude"))
        self.max_mag_check.setText(_translate("filter_parameter_widget_base", "Max"))
        self.min_mag_check.setText(_translate("filter_parameter_widget_base", "Min"))
        self.time_coverage_group.setTitle(_translate("filter_parameter_widget_base", "Time Coverage"))
        self.min_time_check.setText(_translate("filter_parameter_widget_base", "Start"))
        self.fdsn_event_start_date.setDisplayFormat(_translate("filter_parameter_widget_base", "yyyy-MM-dd hh:mm:ss"))
        self.fdsn_event_end_date.setDisplayFormat(_translate("filter_parameter_widget_base", "yyyy-MM-dd hh:mm:ss"))
        self.max_time_check.setText(_translate("filter_parameter_widget_base", "End"))
        self.limit_extent_checkbox.setTitle(_translate("filter_parameter_widget_base", "Geographical Coverage"))
        self.label_circ_radius.setText(_translate("filter_parameter_widget_base", "Radius"))
        self.lat_max_checkbox.setText(_translate("filter_parameter_widget_base", "Max"))
        self.radio_rectangular_area.setText(_translate("filter_parameter_widget_base", "Rectangular area"))
        self.label_rect_long.setText(_translate("filter_parameter_widget_base", "Longitude"))
        self.long_max_checkbox.setText(_translate("filter_parameter_widget_base", "Max"))
        self.circle_center_draw_on_map.setText(_translate("filter_parameter_widget_base", "Select the circle center on the map"))
        self.radius_max_checkbox.setText(_translate("filter_parameter_widget_base", "Max"))
        self.label_circ_lat.setText(_translate("filter_parameter_widget_base", "Latitude"))
        self.label_circ_long.setText(_translate("filter_parameter_widget_base", "Longitude"))
        self.radio_circular_area.setText(_translate("filter_parameter_widget_base", "Circular area"))
        self.label_circ_center.setText(_translate("filter_parameter_widget_base", "Center"))
        self.long_min_checkbox.setText(_translate("filter_parameter_widget_base", "Min"))
        self.rect_extent_draw_on_map.setText(_translate("filter_parameter_widget_base", "Draw the bounding box on the map"))
        self.label_rect_lat.setText(_translate("filter_parameter_widget_base", "Latitude"))
        self.radius_min_checkbox.setText(_translate("filter_parameter_widget_base", "Min"))
        self.lat_min_checkbox.setText(_translate("filter_parameter_widget_base", "Min"))
        self.button_customize_areas.setText(_translate("filter_parameter_widget_base", "Customize…"))
        self.radio_predefined_area.setText(_translate("filter_parameter_widget_base", "Predefined area"))
        self.macroseismic_data_group.setTitle(_translate("filter_parameter_widget_base", "Macroseismic Data"))
        self.earthquake_number_mdps_greater_check.setText(_translate("filter_parameter_widget_base", "Only earthquakes with a number of MDPs greater than"))
        self.earthquake_max_intensity_greater_check.setText(_translate("filter_parameter_widget_base", "Only earthquakes with a max intensity greater than"))
        self.macroseismic_data_group_2.setTitle(_translate("filter_parameter_widget_base", "Other Parameters"))
        self.event_type_check.setText(_translate("filter_parameter_widget_base", "Filter by event type"))
        self.events_updated_after_check.setText(_translate("filter_parameter_widget_base", "Records updated after"))
        self.events_updated_after.setDisplayFormat(_translate("filter_parameter_widget_base", "yyyy-MM-dd"))
from qquake.gui.output_options_widget import OutputOptionsWidget
from qquake.gui.output_table_options_widget import OutputTableOptionsWidget
