# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\giorg\AppData\Roaming\QGIS\QGIS3\profiles\qquake\python\plugins\qquake\ui\predefined_areas_widget_base.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_predefined_areas_widget_base(object):
    def setupUi(self, predefined_areas_widget_base):
        predefined_areas_widget_base.setObjectName("predefined_areas_widget_base")
        predefined_areas_widget_base.resize(613, 402)
        self.gridLayout = QtWidgets.QGridLayout(predefined_areas_widget_base)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(predefined_areas_widget_base)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 1, 1, 1)
        self.region_list = QtWidgets.QListWidget(predefined_areas_widget_base)
        self.region_list.setObjectName("region_list")
        self.gridLayout_2.addWidget(self.region_list, 0, 0, 7, 1)
        self.label_4 = QtWidgets.QLabel(predefined_areas_widget_base)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 1, 1, 1)
        self.spin_min_lat = QtWidgets.QDoubleSpinBox(predefined_areas_widget_base)
        self.spin_min_lat.setDecimals(4)
        self.spin_min_lat.setMinimum(-90.0)
        self.spin_min_lat.setMaximum(90.0)
        self.spin_min_lat.setObjectName("spin_min_lat")
        self.gridLayout_2.addWidget(self.spin_min_lat, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 6, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_add = QtWidgets.QPushButton(predefined_areas_widget_base)
        self.button_add.setObjectName("button_add")
        self.horizontalLayout.addWidget(self.button_add)
        self.button_remove = QtWidgets.QPushButton(predefined_areas_widget_base)
        self.button_remove.setObjectName("button_remove")
        self.horizontalLayout.addWidget(self.button_remove)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 7, 0, 1, 1)
        self.edit_label = QtWidgets.QLineEdit(predefined_areas_widget_base)
        self.edit_label.setObjectName("edit_label")
        self.gridLayout_2.addWidget(self.edit_label, 0, 2, 1, 1)
        self.spin_min_long = QtWidgets.QDoubleSpinBox(predefined_areas_widget_base)
        self.spin_min_long.setDecimals(4)
        self.spin_min_long.setMinimum(-180.0)
        self.spin_min_long.setMaximum(180.0)
        self.spin_min_long.setObjectName("spin_min_long")
        self.gridLayout_2.addWidget(self.spin_min_long, 1, 2, 1, 1)
        self.spin_max_long = QtWidgets.QDoubleSpinBox(predefined_areas_widget_base)
        self.spin_max_long.setDecimals(4)
        self.spin_max_long.setMinimum(-180.0)
        self.spin_max_long.setMaximum(180.0)
        self.spin_max_long.setObjectName("spin_max_long")
        self.gridLayout_2.addWidget(self.spin_max_long, 2, 2, 1, 1)
        self.spin_max_lat = QtWidgets.QDoubleSpinBox(predefined_areas_widget_base)
        self.spin_max_lat.setDecimals(4)
        self.spin_max_lat.setMinimum(-90.0)
        self.spin_max_lat.setMaximum(90.0)
        self.spin_max_lat.setObjectName("spin_max_lat")
        self.gridLayout_2.addWidget(self.spin_max_lat, 4, 2, 1, 1)
        self.label = QtWidgets.QLabel(predefined_areas_widget_base)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(predefined_areas_widget_base)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(predefined_areas_widget_base)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 1, 1, 1)
        self.button_draw_on_map = QtWidgets.QPushButton(predefined_areas_widget_base)
        self.button_draw_on_map.setObjectName("button_draw_on_map")
        self.gridLayout_2.addWidget(self.button_draw_on_map, 5, 1, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)

        self.retranslateUi(predefined_areas_widget_base)
        QtCore.QMetaObject.connectSlotsByName(predefined_areas_widget_base)

    def retranslateUi(self, predefined_areas_widget_base):
        _translate = QtCore.QCoreApplication.translate
        predefined_areas_widget_base.setWindowTitle(_translate("predefined_areas_widget_base", "Form"))
        self.label_5.setText(_translate("predefined_areas_widget_base", "Maximum latitude"))
        self.label_4.setText(_translate("predefined_areas_widget_base", "Minimum latitude"))
        self.button_add.setText(_translate("predefined_areas_widget_base", "Add"))
        self.button_remove.setText(_translate("predefined_areas_widget_base", "Remove"))
        self.label.setText(_translate("predefined_areas_widget_base", "Label"))
        self.label_3.setText(_translate("predefined_areas_widget_base", "Maximum longitude"))
        self.label_2.setText(_translate("predefined_areas_widget_base", "Minimum longitude"))
        self.button_draw_on_map.setText(_translate("predefined_areas_widget_base", "Draw the Bounding Box on the Map"))
