# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\giorg\AppData\Roaming\QGIS\QGIS3\profiles\qquake\python\plugins\qquake\ui\qquake_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QQuakeDialogBase(object):
    def setupUi(self, QQuakeDialogBase):
        QQuakeDialogBase.setObjectName("QQuakeDialogBase")
        QQuakeDialogBase.resize(1082, 901)
        self.verticalLayout = QtWidgets.QVBoxLayout(QQuakeDialogBase)
        self.verticalLayout.setObjectName("verticalLayout")
        self.service_tab_widget = QtWidgets.QTabWidget(QQuakeDialogBase)
        self.service_tab_widget.setTabPosition(QtWidgets.QTabWidget.North)
        self.service_tab_widget.setTabsClosable(False)
        self.service_tab_widget.setMovable(False)
        self.service_tab_widget.setObjectName("service_tab_widget")
        self.fdsn_event_tab = QtWidgets.QWidget()
        self.fdsn_event_tab.setObjectName("fdsn_event_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.fdsn_event_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.fdsn_event_tab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fdsn_event_list = QtWidgets.QListWidget(self.layoutWidget)
        self.fdsn_event_list.setObjectName("fdsn_event_list")
        self.verticalLayout_3.addWidget(self.fdsn_event_list)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_fdsn_new_service = QtWidgets.QToolButton(self.layoutWidget)
        self.button_fdsn_new_service.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.button_fdsn_new_service.setObjectName("button_fdsn_new_service")
        self.horizontalLayout.addWidget(self.button_fdsn_new_service)
        self.button_fdsn_edit_service = QtWidgets.QToolButton(self.layoutWidget)
        self.button_fdsn_edit_service.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.button_fdsn_edit_service.setObjectName("button_fdsn_edit_service")
        self.horizontalLayout.addWidget(self.button_fdsn_edit_service)
        self.button_fdsn_rename_service = QtWidgets.QToolButton(self.layoutWidget)
        self.button_fdsn_rename_service.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.button_fdsn_rename_service.setObjectName("button_fdsn_rename_service")
        self.horizontalLayout.addWidget(self.button_fdsn_rename_service)
        self.button_fdsn_remove_service = QtWidgets.QToolButton(self.layoutWidget)
        self.button_fdsn_remove_service.setObjectName("button_fdsn_remove_service")
        self.horizontalLayout.addWidget(self.button_fdsn_remove_service)
        self.button_fdsn_export_service = QtWidgets.QToolButton(self.layoutWidget)
        self.button_fdsn_export_service.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.button_fdsn_export_service.setObjectName("button_fdsn_export_service")
        self.horizontalLayout.addWidget(self.button_fdsn_export_service)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setMinimumSize(QtCore.QSize(650, 0))
        self.widget.setBaseSize(QtCore.QSize(0, 0))
        self.widget.setObjectName("widget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.fdsn_tab_widget = QtWidgets.QTabWidget(self.widget)
        self.fdsn_tab_widget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fdsn_tab_widget.sizePolicy().hasHeightForWidth())
        self.fdsn_tab_widget.setSizePolicy(sizePolicy)
        self.fdsn_tab_widget.setObjectName("fdsn_tab_widget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.fdsn_event_filter_container = QtWidgets.QWidget(self.tab_5)
        self.fdsn_event_filter_container.setObjectName("fdsn_event_filter_container")
        self.verticalLayout_12.addWidget(self.fdsn_event_filter_container)
        self.fdsn_tab_widget.addTab(self.tab_5, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_11)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.fdsn_by_id_container = QtWidgets.QWidget(self.tab_11)
        self.fdsn_by_id_container.setObjectName("fdsn_by_id_container")
        self.verticalLayout_10.addWidget(self.fdsn_by_id_container)
        self.fdsn_tab_widget.addTab(self.tab_11, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.tab_14)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.fdsn_by_url_container = QtWidgets.QWidget(self.tab_14)
        self.fdsn_by_url_container.setObjectName("fdsn_by_url_container")
        self.verticalLayout_21.addWidget(self.fdsn_by_url_container)
        self.fdsn_tab_widget.addTab(self.tab_14, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.earthquake_service_info_container = QtWidgets.QWidget(self.tab_6)
        self.earthquake_service_info_container.setObjectName("earthquake_service_info_container")
        self.verticalLayout_5.addWidget(self.earthquake_service_info_container)
        self.fdsn_tab_widget.addTab(self.tab_6, "")
        self.verticalLayout_11.addWidget(self.fdsn_tab_widget)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        self.fdsn_event_url_text_browser = QtWidgets.QTextBrowser(self.fdsn_event_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fdsn_event_url_text_browser.sizePolicy().hasHeightForWidth())
        self.fdsn_event_url_text_browser.setSizePolicy(sizePolicy)
        self.fdsn_event_url_text_browser.setMinimumSize(QtCore.QSize(0, 80))
        self.fdsn_event_url_text_browser.setMaximumSize(QtCore.QSize(16777215, 80))
        self.fdsn_event_url_text_browser.setBaseSize(QtCore.QSize(10, 10))
        self.fdsn_event_url_text_browser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fdsn_event_url_text_browser.setOpenExternalLinks(True)
        self.fdsn_event_url_text_browser.setObjectName("fdsn_event_url_text_browser")
        self.gridLayout_2.addWidget(self.fdsn_event_url_text_browser, 1, 0, 1, 1)
        self.service_tab_widget.addTab(self.fdsn_event_tab, "")
        self.fdsn_macro_tab = QtWidgets.QWidget()
        self.fdsn_macro_tab.setObjectName("fdsn_macro_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.fdsn_macro_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter_2 = QtWidgets.QSplitter(self.fdsn_macro_tab)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.fdsn_macro_list = QtWidgets.QListWidget(self.layoutWidget1)
        self.fdsn_macro_list.setBaseSize(QtCore.QSize(130, 0))
        self.fdsn_macro_list.setObjectName("fdsn_macro_list")
        self.verticalLayout_19.addWidget(self.fdsn_macro_list)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_macro_new_service = QtWidgets.QToolButton(self.layoutWidget1)
        self.button_macro_new_service.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.button_macro_new_service.setObjectName("button_macro_new_service")
        self.horizontalLayout_2.addWidget(self.button_macro_new_service)
        self.button_macro_edit_service = QtWidgets.QToolButton(self.layoutWidget1)
        self.button_macro_edit_service.setObjectName("button_macro_edit_service")
        self.horizontalLayout_2.addWidget(self.button_macro_edit_service)
        self.button_macro_rename_service = QtWidgets.QToolButton(self.layoutWidget1)
        self.button_macro_rename_service.setObjectName("button_macro_rename_service")
        self.horizontalLayout_2.addWidget(self.button_macro_rename_service)
        self.button_macro_remove_service = QtWidgets.QToolButton(self.layoutWidget1)
        self.button_macro_remove_service.setObjectName("button_macro_remove_service")
        self.horizontalLayout_2.addWidget(self.button_macro_remove_service)
        self.button_macro_export_service = QtWidgets.QToolButton(self.layoutWidget1)
        self.button_macro_export_service.setObjectName("button_macro_export_service")
        self.horizontalLayout_2.addWidget(self.button_macro_export_service)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_19.addLayout(self.horizontalLayout_2)
        self.widget_3 = QtWidgets.QWidget(self.splitter_2)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.macro_tab_widget = QtWidgets.QTabWidget(self.widget_3)
        self.macro_tab_widget.setMinimumSize(QtCore.QSize(600, 0))
        self.macro_tab_widget.setObjectName("macro_tab_widget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.macro_filter_container = QtWidgets.QWidget(self.tab_3)
        self.macro_filter_container.setObjectName("macro_filter_container")
        self.verticalLayout_14.addWidget(self.macro_filter_container)
        self.macro_tab_widget.addTab(self.tab_3, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_12)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.macro_by_id_container = QtWidgets.QWidget(self.tab_12)
        self.macro_by_id_container.setObjectName("macro_by_id_container")
        self.verticalLayout_15.addWidget(self.macro_by_id_container)
        self.macro_tab_widget.addTab(self.tab_12, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.tab_15)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.macro_by_url_container = QtWidgets.QWidget(self.tab_15)
        self.macro_by_url_container.setObjectName("macro_by_url_container")
        self.verticalLayout_22.addWidget(self.macro_by_url_container)
        self.macro_tab_widget.addTab(self.tab_15, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.macro_service_info_container = QtWidgets.QWidget(self.tab_4)
        self.macro_service_info_container.setObjectName("macro_service_info_container")
        self.verticalLayout_6.addWidget(self.macro_service_info_container)
        self.macro_tab_widget.addTab(self.tab_4, "")
        self.verticalLayout_13.addWidget(self.macro_tab_widget)
        self.gridLayout_3.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.fdsn_macro_url_text_browser = QtWidgets.QTextBrowser(self.fdsn_macro_tab)
        self.fdsn_macro_url_text_browser.setMinimumSize(QtCore.QSize(0, 80))
        self.fdsn_macro_url_text_browser.setMaximumSize(QtCore.QSize(16777215, 80))
        self.fdsn_macro_url_text_browser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fdsn_macro_url_text_browser.setOpenExternalLinks(True)
        self.fdsn_macro_url_text_browser.setObjectName("fdsn_macro_url_text_browser")
        self.gridLayout_3.addWidget(self.fdsn_macro_url_text_browser, 1, 0, 1, 1)
        self.service_tab_widget.addTab(self.fdsn_macro_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitter_3 = QtWidgets.QSplitter(self.tab)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setChildrenCollapsible(False)
        self.splitter_3.setObjectName("splitter_3")
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fdsn_station_list = QtWidgets.QListWidget(self.layoutWidget2)
        self.fdsn_station_list.setObjectName("fdsn_station_list")
        self.verticalLayout_2.addWidget(self.fdsn_station_list)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_station_new_service = QtWidgets.QToolButton(self.layoutWidget2)
        self.button_station_new_service.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.button_station_new_service.setObjectName("button_station_new_service")
        self.horizontalLayout_3.addWidget(self.button_station_new_service)
        self.button_station_edit_service = QtWidgets.QToolButton(self.layoutWidget2)
        self.button_station_edit_service.setObjectName("button_station_edit_service")
        self.horizontalLayout_3.addWidget(self.button_station_edit_service)
        self.button_station_rename_service = QtWidgets.QToolButton(self.layoutWidget2)
        self.button_station_rename_service.setObjectName("button_station_rename_service")
        self.horizontalLayout_3.addWidget(self.button_station_rename_service)
        self.button_station_remove_service = QtWidgets.QToolButton(self.layoutWidget2)
        self.button_station_remove_service.setObjectName("button_station_remove_service")
        self.horizontalLayout_3.addWidget(self.button_station_remove_service)
        self.button_station_export_service = QtWidgets.QToolButton(self.layoutWidget2)
        self.button_station_export_service.setObjectName("button_station_export_service")
        self.horizontalLayout_3.addWidget(self.button_station_export_service)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.widget_4 = QtWidgets.QWidget(self.splitter_3)
        self.widget_4.setMinimumSize(QtCore.QSize(600, 0))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.fdsnstation_tab_widget = QtWidgets.QTabWidget(self.widget_4)
        self.fdsnstation_tab_widget.setObjectName("fdsnstation_tab_widget")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_9)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.station_filter_container = QtWidgets.QWidget(self.tab_9)
        self.station_filter_container.setObjectName("station_filter_container")
        self.verticalLayout_8.addWidget(self.station_filter_container)
        self.fdsnstation_tab_widget.addTab(self.tab_9, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.tab_13)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.station_by_id_container = QtWidgets.QWidget(self.tab_13)
        self.station_by_id_container.setObjectName("station_by_id_container")
        self.verticalLayout_18.addWidget(self.station_by_id_container)
        self.fdsnstation_tab_widget.addTab(self.tab_13, "")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_16)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.station_by_url_container = QtWidgets.QWidget(self.tab_16)
        self.station_by_url_container.setObjectName("station_by_url_container")
        self.gridLayout_7.addWidget(self.station_by_url_container, 0, 0, 1, 1)
        self.fdsnstation_tab_widget.addTab(self.tab_16, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.station_service_info_container = QtWidgets.QWidget(self.tab_10)
        self.station_service_info_container.setObjectName("station_service_info_container")
        self.verticalLayout_9.addWidget(self.station_service_info_container)
        self.fdsnstation_tab_widget.addTab(self.tab_10, "")
        self.verticalLayout_16.addWidget(self.fdsnstation_tab_widget)
        self.gridLayout_5.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.fdsn_station_url_text_browser = QtWidgets.QTextBrowser(self.tab)
        self.fdsn_station_url_text_browser.setMinimumSize(QtCore.QSize(0, 80))
        self.fdsn_station_url_text_browser.setMaximumSize(QtCore.QSize(16777215, 80))
        self.fdsn_station_url_text_browser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fdsn_station_url_text_browser.setOpenExternalLinks(True)
        self.fdsn_station_url_text_browser.setObjectName("fdsn_station_url_text_browser")
        self.gridLayout_5.addWidget(self.fdsn_station_url_text_browser, 1, 0, 1, 1)
        self.service_tab_widget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.splitter_4 = QtWidgets.QSplitter(self.tab_2)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setChildrenCollapsible(False)
        self.splitter_4.setObjectName("splitter_4")
        self.layoutWidget3 = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.ogc_combo = QtWidgets.QComboBox(self.layoutWidget3)
        self.ogc_combo.setObjectName("ogc_combo")
        self.verticalLayout_20.addWidget(self.ogc_combo)
        self.ogc_list = QtWidgets.QTreeView(self.layoutWidget3)
        self.ogc_list.setHeaderHidden(True)
        self.ogc_list.setObjectName("ogc_list")
        self.verticalLayout_20.addWidget(self.ogc_list)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.button_ogc_new_service = QtWidgets.QToolButton(self.layoutWidget3)
        self.button_ogc_new_service.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.button_ogc_new_service.setObjectName("button_ogc_new_service")
        self.horizontalLayout_4.addWidget(self.button_ogc_new_service)
        self.button_ogc_edit_service = QtWidgets.QToolButton(self.layoutWidget3)
        self.button_ogc_edit_service.setObjectName("button_ogc_edit_service")
        self.horizontalLayout_4.addWidget(self.button_ogc_edit_service)
        self.button_ogc_rename_service = QtWidgets.QToolButton(self.layoutWidget3)
        self.button_ogc_rename_service.setObjectName("button_ogc_rename_service")
        self.horizontalLayout_4.addWidget(self.button_ogc_rename_service)
        self.button_ogc_remove_service = QtWidgets.QToolButton(self.layoutWidget3)
        self.button_ogc_remove_service.setObjectName("button_ogc_remove_service")
        self.horizontalLayout_4.addWidget(self.button_ogc_remove_service)
        self.button_ogc_export_service = QtWidgets.QToolButton(self.layoutWidget3)
        self.button_ogc_export_service.setObjectName("button_ogc_export_service")
        self.horizontalLayout_4.addWidget(self.button_ogc_export_service)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_20.addLayout(self.horizontalLayout_4)
        self.scrollArea_4 = QtWidgets.QScrollArea(self.splitter_4)
        self.scrollArea_4.setMinimumSize(QtCore.QSize(600, 0))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 598, 764))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ogc_tab_widget = QtWidgets.QTabWidget(self.scrollAreaWidgetContents_4)
        self.ogc_tab_widget.setObjectName("ogc_tab_widget")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ogc_widget_container = QtWidgets.QWidget(self.tab_7)
        self.ogc_widget_container.setObjectName("ogc_widget_container")
        self.verticalLayout_4.addWidget(self.ogc_widget_container)
        self.ogc_tab_widget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.ogc_service_info_container = QtWidgets.QWidget(self.tab_8)
        self.ogc_service_info_container.setObjectName("ogc_service_info_container")
        self.verticalLayout_7.addWidget(self.ogc_service_info_container)
        self.ogc_tab_widget.addTab(self.tab_8, "")
        self.gridLayout_4.addWidget(self.ogc_tab_widget, 0, 0, 1, 1)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_6.addWidget(self.splitter_4, 0, 0, 1, 1)
        self.service_tab_widget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.service_tab_widget)
        self.progressBar = QtWidgets.QProgressBar(QQuakeDialogBase)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.button_box = QtWidgets.QDialogButtonBox(QQuakeDialogBase)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(QQuakeDialogBase)
        self.service_tab_widget.setCurrentIndex(0)
        self.fdsn_tab_widget.setCurrentIndex(0)
        self.macro_tab_widget.setCurrentIndex(0)
        self.fdsnstation_tab_widget.setCurrentIndex(0)
        self.ogc_tab_widget.setCurrentIndex(0)
        self.button_box.rejected.connect(QQuakeDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(QQuakeDialogBase)

    def retranslateUi(self, QQuakeDialogBase):
        _translate = QtCore.QCoreApplication.translate
        QQuakeDialogBase.setWindowTitle(_translate("QQuakeDialogBase", "QQuake v1.6"))
        self.button_fdsn_new_service.setText(_translate("QQuakeDialogBase", "Add"))
        self.button_fdsn_edit_service.setText(_translate("QQuakeDialogBase", "Edit"))
        self.button_fdsn_rename_service.setText(_translate("QQuakeDialogBase", "Rename"))
        self.button_fdsn_remove_service.setText(_translate("QQuakeDialogBase", "Remove"))
        self.button_fdsn_export_service.setText(_translate("QQuakeDialogBase", "Export"))
        self.fdsn_tab_widget.setTabText(self.fdsn_tab_widget.indexOf(self.tab_5), _translate("QQuakeDialogBase", "Search by Parameters"))
        self.fdsn_tab_widget.setTabText(self.fdsn_tab_widget.indexOf(self.tab_11), _translate("QQuakeDialogBase", "Search by Identifiers"))
        self.fdsn_tab_widget.setTabText(self.fdsn_tab_widget.indexOf(self.tab_14), _translate("QQuakeDialogBase", "Load QuakeML Directly"))
        self.fdsn_tab_widget.setTabText(self.fdsn_tab_widget.indexOf(self.tab_6), _translate("QQuakeDialogBase", "Service Information"))
        self.service_tab_widget.setTabText(self.service_tab_widget.indexOf(self.fdsn_event_tab), _translate("QQuakeDialogBase", "Earthquakes parameters"))
        self.button_macro_new_service.setText(_translate("QQuakeDialogBase", "Add"))
        self.button_macro_edit_service.setText(_translate("QQuakeDialogBase", "Edit"))
        self.button_macro_rename_service.setText(_translate("QQuakeDialogBase", "Rename"))
        self.button_macro_remove_service.setText(_translate("QQuakeDialogBase", "Remove"))
        self.button_macro_export_service.setText(_translate("QQuakeDialogBase", "Export"))
        self.macro_tab_widget.setTabText(self.macro_tab_widget.indexOf(self.tab_3), _translate("QQuakeDialogBase", "Search by Parameters"))
        self.macro_tab_widget.setTabText(self.macro_tab_widget.indexOf(self.tab_12), _translate("QQuakeDialogBase", "Search by Identifiers"))
        self.macro_tab_widget.setTabText(self.macro_tab_widget.indexOf(self.tab_15), _translate("QQuakeDialogBase", "Load QuakeML Directly"))
        self.macro_tab_widget.setTabText(self.macro_tab_widget.indexOf(self.tab_4), _translate("QQuakeDialogBase", "Service Information"))
        self.service_tab_widget.setTabText(self.service_tab_widget.indexOf(self.fdsn_macro_tab), _translate("QQuakeDialogBase", "Macroseismic data"))
        self.button_station_new_service.setText(_translate("QQuakeDialogBase", "Add"))
        self.button_station_edit_service.setText(_translate("QQuakeDialogBase", "Edit"))
        self.button_station_rename_service.setText(_translate("QQuakeDialogBase", "Rename"))
        self.button_station_remove_service.setText(_translate("QQuakeDialogBase", "Remove"))
        self.button_station_export_service.setText(_translate("QQuakeDialogBase", "Export"))
        self.fdsnstation_tab_widget.setTabText(self.fdsnstation_tab_widget.indexOf(self.tab_9), _translate("QQuakeDialogBase", "Search by Parameters"))
        self.fdsnstation_tab_widget.setTabText(self.fdsnstation_tab_widget.indexOf(self.tab_13), _translate("QQuakeDialogBase", "Search by Identifiers"))
        self.fdsnstation_tab_widget.setTabText(self.fdsnstation_tab_widget.indexOf(self.tab_16), _translate("QQuakeDialogBase", "Load StationXML Directly"))
        self.fdsnstation_tab_widget.setTabText(self.fdsnstation_tab_widget.indexOf(self.tab_10), _translate("QQuakeDialogBase", "Service Information"))
        self.service_tab_widget.setTabText(self.service_tab_widget.indexOf(self.tab), _translate("QQuakeDialogBase", "Seismic stations"))
        self.button_ogc_new_service.setText(_translate("QQuakeDialogBase", "Add"))
        self.button_ogc_edit_service.setText(_translate("QQuakeDialogBase", "Edit"))
        self.button_ogc_rename_service.setText(_translate("QQuakeDialogBase", "Rename"))
        self.button_ogc_remove_service.setText(_translate("QQuakeDialogBase", "Remove"))
        self.button_ogc_export_service.setText(_translate("QQuakeDialogBase", "Export"))
        self.ogc_tab_widget.setTabText(self.ogc_tab_widget.indexOf(self.tab_7), _translate("QQuakeDialogBase", "Service Configuration"))
        self.ogc_tab_widget.setTabText(self.ogc_tab_widget.indexOf(self.tab_8), _translate("QQuakeDialogBase", "Service Information"))
        self.service_tab_widget.setTabText(self.service_tab_widget.indexOf(self.tab_2), _translate("QQuakeDialogBase", "OGC services"))
