# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\giorg\AppData\Roaming\QGIS\QGIS3\profiles\qquake\python\plugins\qquake\ui\service_configuration_widget_base.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_service_configuration_widget_base(object):
    def setupUi(self, service_configuration_widget_base):
        service_configuration_widget_base.setObjectName("service_configuration_widget_base")
        service_configuration_widget_base.resize(701, 888)
        self.gridLayout_4 = QtWidgets.QGridLayout(service_configuration_widget_base)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.message_bar = QgsMessageBar(service_configuration_widget_base)
        self.message_bar.setObjectName("message_bar")
        self.gridLayout_4.addWidget(self.message_bar, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(service_configuration_widget_base)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -693, 715, 2012))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, -1, 9)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.mdp_preset_label = QtWidgets.QLabel(self.groupBox_4)
        self.mdp_preset_label.setObjectName("mdp_preset_label")
        self.gridLayout_8.addWidget(self.mdp_preset_label, 3, 0, 1, 1)
        self.label_qml_events = QtWidgets.QLabel(self.groupBox_4)
        self.label_qml_events.setObjectName("label_qml_events")
        self.gridLayout_8.addWidget(self.label_qml_events, 0, 0, 1, 1)
        self.qml_style_name_combo_mdp = QtWidgets.QComboBox(self.groupBox_4)
        self.qml_style_name_combo_mdp.setObjectName("qml_style_name_combo_mdp")
        self.gridLayout_8.addWidget(self.qml_style_name_combo_mdp, 3, 1, 1, 1)
        self.label_mdp_url = QtWidgets.QLabel(self.groupBox_4)
        self.label_mdp_url.setObjectName("label_mdp_url")
        self.gridLayout_8.addWidget(self.label_mdp_url, 2, 0, 1, 1)
        self.qml_style_url_edit_mdp = QtWidgets.QLineEdit(self.groupBox_4)
        self.qml_style_url_edit_mdp.setObjectName("qml_style_url_edit_mdp")
        self.gridLayout_8.addWidget(self.qml_style_url_edit_mdp, 2, 1, 1, 1)
        self.label_preset_style_events = QtWidgets.QLabel(self.groupBox_4)
        self.label_preset_style_events.setObjectName("label_preset_style_events")
        self.gridLayout_8.addWidget(self.label_preset_style_events, 1, 0, 1, 1)
        self.label_stations_url = QtWidgets.QLabel(self.groupBox_4)
        self.label_stations_url.setObjectName("label_stations_url")
        self.gridLayout_8.addWidget(self.label_stations_url, 4, 0, 1, 1)
        self.qml_style_name_combo_events = QtWidgets.QComboBox(self.groupBox_4)
        self.qml_style_name_combo_events.setObjectName("qml_style_name_combo_events")
        self.gridLayout_8.addWidget(self.qml_style_name_combo_events, 1, 1, 1, 1)
        self.qml_style_url_edit_events = QtWidgets.QLineEdit(self.groupBox_4)
        self.qml_style_url_edit_events.setObjectName("qml_style_url_edit_events")
        self.gridLayout_8.addWidget(self.qml_style_url_edit_events, 0, 1, 1, 1)
        self.label_preset_name_stations = QtWidgets.QLabel(self.groupBox_4)
        self.label_preset_name_stations.setObjectName("label_preset_name_stations")
        self.gridLayout_8.addWidget(self.label_preset_name_stations, 5, 0, 1, 1)
        self.qml_style_name_combo_stations = QtWidgets.QComboBox(self.groupBox_4)
        self.qml_style_name_combo_stations.setObjectName("qml_style_name_combo_stations")
        self.gridLayout_8.addWidget(self.qml_style_name_combo_stations, 5, 1, 1, 1)
        self.qml_style_url_edit_stations = QtWidgets.QLineEdit(self.groupBox_4)
        self.qml_style_url_edit_stations.setObjectName("qml_style_url_edit_stations")
        self.gridLayout_8.addWidget(self.qml_style_url_edit_stations, 4, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 7, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.start_date_edit = QgsDateTimeEdit(self.groupBox_3)
        self.start_date_edit.setObjectName("start_date_edit")
        self.gridLayout_7.addWidget(self.start_date_edit, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 0, 0, 1, 1)
        self.end_date_edit = QgsDateTimeEdit(self.groupBox_3)
        self.end_date_edit.setObjectName("end_date_edit")
        self.gridLayout_7.addWidget(self.end_date_edit, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 3, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.data_license_url_edit = QtWidgets.QLineEdit(self.groupBox)
        self.data_license_url_edit.setObjectName("data_license_url_edit")
        self.gridLayout_2.addWidget(self.data_license_url_edit, 8, 1, 1, 1)
        self.service_description_url_edit = QtWidgets.QLineEdit(self.groupBox)
        self.service_description_url_edit.setObjectName("service_description_url_edit")
        self.gridLayout_2.addWidget(self.service_description_url_edit, 11, 1, 1, 1)
        self.data_provider_edit = QtWidgets.QLineEdit(self.groupBox)
        self.data_provider_edit.setObjectName("data_provider_edit")
        self.gridLayout_2.addWidget(self.data_provider_edit, 12, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 12, 0, 1, 1)
        self.data_provider_url_edit = QtWidgets.QLineEdit(self.groupBox)
        self.data_provider_url_edit.setObjectName("data_provider_url_edit")
        self.gridLayout_2.addWidget(self.data_provider_url_edit, 13, 1, 1, 1)
        self.data_description_url_edit = QtWidgets.QLineEdit(self.groupBox)
        self.data_description_url_edit.setObjectName("data_description_url_edit")
        self.gridLayout_2.addWidget(self.data_description_url_edit, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.title_edit = QtWidgets.QLineEdit(self.groupBox)
        self.title_edit.setObjectName("title_edit")
        self.gridLayout_2.addWidget(self.title_edit, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 13, 0, 1, 1)
        self.data_description_edit = QtWidgets.QLineEdit(self.groupBox)
        self.data_description_edit.setObjectName("data_description_edit")
        self.gridLayout_2.addWidget(self.data_description_edit, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 8, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 14, 0, 1, 1)
        self.data_license_edit = QtWidgets.QLineEdit(self.groupBox)
        self.data_license_edit.setObjectName("data_license_edit")
        self.gridLayout_2.addWidget(self.data_license_edit, 7, 1, 1, 1)
        self.webservice_manual_url_edit = QtWidgets.QLineEdit(self.groupBox)
        self.webservice_manual_url_edit.setObjectName("webservice_manual_url_edit")
        self.gridLayout_2.addWidget(self.webservice_manual_url_edit, 14, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 10, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 15, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 11, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 7, 0, 1, 1)
        self.service_description_edit = QtWidgets.QLineEdit(self.groupBox)
        self.service_description_edit.setObjectName("service_description_edit")
        self.gridLayout_2.addWidget(self.service_description_edit, 10, 1, 1, 1)
        self.publications_text_edit = QtWidgets.QTextBrowser(self.groupBox)
        self.publications_text_edit.setReadOnly(False)
        self.publications_text_edit.setAcceptRichText(False)
        self.publications_text_edit.setObjectName("publications_text_edit")
        self.gridLayout_2.addWidget(self.publications_text_edit, 15, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 4, 0, 1, 1)
        self.group_label = QtWidgets.QLabel(self.groupBox)
        self.group_label.setObjectName("group_label")
        self.gridLayout_2.addWidget(self.group_label, 9, 0, 1, 1)
        self.group_edit = QtWidgets.QLineEdit(self.groupBox)
        self.group_edit.setObjectName("group_edit")
        self.gridLayout_2.addWidget(self.group_edit, 9, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.group_ogc_layers = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.group_ogc_layers.setObjectName("group_ogc_layers")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.group_ogc_layers)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ogc_layers_edit = QgsCodeEditor(self.group_ogc_layers)
        self.ogc_layers_edit.setMinimumSize(QtCore.QSize(0, 300))
        self.ogc_layers_edit.setObjectName("ogc_layers_edit")
        self.verticalLayout.addWidget(self.ogc_layers_edit)
        self.gridLayout.addWidget(self.group_ogc_layers, 8, 0, 1, 1)
        self.group_capabilities = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.group_capabilities.setObjectName("group_capabilities")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.group_capabilities)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.check_radius_of_circular_area_is_specified_in_km = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_radius_of_circular_area_is_specified_in_km.setObjectName("check_radius_of_circular_area_is_specified_in_km")
        self.gridLayout_5.addWidget(self.check_radius_of_circular_area_is_specified_in_km, 3, 1, 1, 1)
        self.check_filter_by_magnitude_type = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_filter_by_magnitude_type.setObjectName("check_filter_by_magnitude_type")
        self.gridLayout_5.addWidget(self.check_filter_by_magnitude_type, 9, 0, 1, 1)
        self.check_can_include_arrivals = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_can_include_arrivals.setObjectName("check_can_include_arrivals")
        self.gridLayout_5.addWidget(self.check_can_include_arrivals, 14, 0, 1, 1)
        self.check_filter_data_updated_after = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_filter_data_updated_after.setObjectName("check_filter_data_updated_after")
        self.gridLayout_5.addWidget(self.check_filter_data_updated_after, 4, 0, 1, 1)
        self.check_filter_by_originid = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_filter_by_originid.setObjectName("check_filter_by_originid")
        self.gridLayout_5.addWidget(self.check_filter_by_originid, 1, 0, 1, 1)
        self.check_can_include_all_origins = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_can_include_all_origins.setObjectName("check_can_include_all_origins")
        self.gridLayout_5.addWidget(self.check_can_include_all_origins, 10, 0, 1, 1)
        self.check_filter_by_contributor = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_filter_by_contributor.setObjectName("check_filter_by_contributor")
        self.gridLayout_5.addWidget(self.check_filter_by_contributor, 6, 0, 1, 1)
        self.check_can_output_kml = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_can_output_kml.setObjectName("check_can_output_kml")
        self.gridLayout_5.addWidget(self.check_can_output_kml, 9, 1, 1, 1)
        self.check_filter_by_event_type = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_filter_by_event_type.setObjectName("check_filter_by_event_type")
        self.gridLayout_5.addWidget(self.check_filter_by_event_type, 8, 0, 1, 1)
        self.check_filter_by_eventid = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_filter_by_eventid.setObjectName("check_filter_by_eventid")
        self.gridLayout_5.addWidget(self.check_filter_by_eventid, 0, 0, 1, 1)
        self.check_can_output_geojson = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_can_output_geojson.setObjectName("check_can_output_geojson")
        self.gridLayout_5.addWidget(self.check_can_output_geojson, 7, 1, 1, 1)
        self.check_can_output_microsoft_xlsx = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_can_output_microsoft_xlsx.setObjectName("check_can_output_microsoft_xlsx")
        self.gridLayout_5.addWidget(self.check_can_output_microsoft_xlsx, 10, 1, 1, 1)
        self.check_can_output_text = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_can_output_text.setObjectName("check_can_output_text")
        self.gridLayout_5.addWidget(self.check_can_output_text, 5, 1, 1, 1)
        self.check_filter_by_magnitudeid = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_filter_by_magnitudeid.setObjectName("check_filter_by_magnitudeid")
        self.gridLayout_5.addWidget(self.check_filter_by_magnitudeid, 2, 0, 1, 1)
        self.check_can_output_xml = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_can_output_xml.setObjectName("check_can_output_xml")
        self.gridLayout_5.addWidget(self.check_can_output_xml, 6, 1, 1, 1)
        self.check_can_filter_using_circular_area = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_can_filter_using_circular_area.setObjectName("check_can_filter_using_circular_area")
        self.gridLayout_5.addWidget(self.check_can_filter_using_circular_area, 2, 1, 1, 1)
        self.check_can_include_all_stations_magnitudes = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_can_include_all_stations_magnitudes.setObjectName("check_can_include_all_stations_magnitudes")
        self.gridLayout_5.addWidget(self.check_can_include_all_stations_magnitudes, 0, 1, 1, 1)
        self.check_can_include_all_origins_multiple = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_can_include_all_origins_multiple.setObjectName("check_can_include_all_origins_multiple")
        self.gridLayout_5.addWidget(self.check_can_include_all_origins_multiple, 11, 0, 1, 1)
        self.check_filter_by_catalog = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_filter_by_catalog.setObjectName("check_filter_by_catalog")
        self.gridLayout_5.addWidget(self.check_filter_by_catalog, 5, 0, 1, 1)
        self.check_filter_by_focalmechanismid = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_filter_by_focalmechanismid.setObjectName("check_filter_by_focalmechanismid")
        self.gridLayout_5.addWidget(self.check_filter_by_focalmechanismid, 3, 0, 1, 1)
        self.check_can_filter_by_depth = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_can_filter_by_depth.setObjectName("check_can_filter_by_depth")
        self.gridLayout_5.addWidget(self.check_can_filter_by_depth, 4, 1, 1, 1)
        self.check_can_include_all_magnitudes = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_can_include_all_magnitudes.setObjectName("check_can_include_all_magnitudes")
        self.gridLayout_5.addWidget(self.check_can_include_all_magnitudes, 12, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.check_has_limit_of_entries = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_has_limit_of_entries.setObjectName("check_has_limit_of_entries")
        self.horizontalLayout.addWidget(self.check_has_limit_of_entries)
        self.spin_has_limit_of_entries = QtWidgets.QSpinBox(self.group_capabilities)
        self.spin_has_limit_of_entries.setMinimumSize(QtCore.QSize(110, 0))
        self.spin_has_limit_of_entries.setMaximum(999999999)
        self.spin_has_limit_of_entries.setObjectName("spin_has_limit_of_entries")
        self.horizontalLayout.addWidget(self.spin_has_limit_of_entries)
        self.label_17 = QtWidgets.QLabel(self.group_capabilities)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout.addWidget(self.label_17)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_5.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.check_filter_by_contributorid = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_filter_by_contributorid.setObjectName("check_filter_by_contributorid")
        self.gridLayout_5.addWidget(self.check_filter_by_contributorid, 7, 0, 1, 1)
        self.check_can_output_json = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_can_output_json.setObjectName("check_can_output_json")
        self.gridLayout_5.addWidget(self.check_can_output_json, 8, 1, 1, 1)
        self.check_can_include_all_magnitudes_multiple = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_can_include_all_magnitudes_multiple.setObjectName("check_can_include_all_magnitudes_multiple")
        self.gridLayout_5.addWidget(self.check_can_include_all_magnitudes_multiple, 13, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.check_http_code_nodata = QtWidgets.QCheckBox(self.group_capabilities)
        self.check_http_code_nodata.setObjectName("check_http_code_nodata")
        self.horizontalLayout_2.addWidget(self.check_http_code_nodata)
        self.combo_http_code_nodata = QtWidgets.QComboBox(self.group_capabilities)
        self.combo_http_code_nodata.setObjectName("combo_http_code_nodata")
        self.horizontalLayout_2.addWidget(self.combo_http_code_nodata)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 11, 1, 1, 1)
        self.gridLayout.addWidget(self.group_capabilities, 6, 0, 1, 1)
        self.group_bounding_box = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.group_bounding_box.setObjectName("group_bounding_box")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.group_bounding_box)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_14 = QtWidgets.QLabel(self.group_bounding_box)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.group_bounding_box)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 3, 0, 1, 1)
        self.min_lat_spin = QtWidgets.QDoubleSpinBox(self.group_bounding_box)
        self.min_lat_spin.setMinimum(-90.0)
        self.min_lat_spin.setMaximum(90.0)
        self.min_lat_spin.setObjectName("min_lat_spin")
        self.gridLayout_3.addWidget(self.min_lat_spin, 0, 1, 1, 1)
        self.max_long_spin = QtWidgets.QDoubleSpinBox(self.group_bounding_box)
        self.max_long_spin.setMinimum(-180.0)
        self.max_long_spin.setMaximum(180.0)
        self.max_long_spin.setObjectName("max_long_spin")
        self.gridLayout_3.addWidget(self.max_long_spin, 3, 1, 1, 1)
        self.min_long_spin = QtWidgets.QDoubleSpinBox(self.group_bounding_box)
        self.min_long_spin.setMinimum(-180.0)
        self.min_long_spin.setMaximum(180.0)
        self.min_long_spin.setObjectName("min_long_spin")
        self.gridLayout_3.addWidget(self.min_long_spin, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.group_bounding_box)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.group_bounding_box)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.max_lat_spin = QtWidgets.QDoubleSpinBox(self.group_bounding_box)
        self.max_lat_spin.setMinimum(-90.0)
        self.max_lat_spin.setMaximum(90.0)
        self.max_lat_spin.setObjectName("max_lat_spin")
        self.gridLayout_3.addWidget(self.max_lat_spin, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.group_bounding_box, 4, 0, 1, 1)
        self.button_load_service_capabilities = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.button_load_service_capabilities.setObjectName("button_load_service_capabilities")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.button_load_service_capabilities)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_9 = QtWidgets.QLabel(self.button_load_service_capabilities)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 0, 0, 1, 1)
        self.button_load_service = QtWidgets.QPushButton(self.button_load_service_capabilities)
        self.button_load_service.setObjectName("button_load_service")
        self.gridLayout_6.addWidget(self.button_load_service, 1, 2, 1, 1)
        self.web_service_url_edit = QtWidgets.QLineEdit(self.button_load_service_capabilities)
        self.web_service_url_edit.setObjectName("web_service_url_edit")
        self.gridLayout_6.addWidget(self.web_service_url_edit, 0, 1, 1, 2)
        self.gridLayout.addWidget(self.button_load_service_capabilities, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 3, 0, 1, 1)

        self.retranslateUi(service_configuration_widget_base)
        QtCore.QMetaObject.connectSlotsByName(service_configuration_widget_base)
        service_configuration_widget_base.setTabOrder(self.scrollArea, self.title_edit)
        service_configuration_widget_base.setTabOrder(self.title_edit, self.data_license_edit)
        service_configuration_widget_base.setTabOrder(self.data_license_edit, self.data_license_url_edit)
        service_configuration_widget_base.setTabOrder(self.data_license_url_edit, self.data_provider_edit)
        service_configuration_widget_base.setTabOrder(self.data_provider_edit, self.data_provider_url_edit)
        service_configuration_widget_base.setTabOrder(self.data_provider_url_edit, self.min_lat_spin)
        service_configuration_widget_base.setTabOrder(self.min_lat_spin, self.max_lat_spin)
        service_configuration_widget_base.setTabOrder(self.max_lat_spin, self.min_long_spin)
        service_configuration_widget_base.setTabOrder(self.min_long_spin, self.max_long_spin)

    def retranslateUi(self, service_configuration_widget_base):
        _translate = QtCore.QCoreApplication.translate
        service_configuration_widget_base.setWindowTitle(_translate("service_configuration_widget_base", "Form"))
        self.groupBox_4.setTitle(_translate("service_configuration_widget_base", "Output Styling"))
        self.mdp_preset_label.setText(_translate("service_configuration_widget_base", "Preset style name (mdps)"))
        self.label_qml_events.setText(_translate("service_configuration_widget_base", "QML style URL (events)"))
        self.label_mdp_url.setText(_translate("service_configuration_widget_base", "QML style URL (mdps)"))
        self.label_preset_style_events.setText(_translate("service_configuration_widget_base", "Preset style name (events)"))
        self.label_stations_url.setText(_translate("service_configuration_widget_base", "QML style URL (stations)"))
        self.label_preset_name_stations.setText(_translate("service_configuration_widget_base", "Preset style name (stations)"))
        self.groupBox_3.setTitle(_translate("service_configuration_widget_base", "Web Service Temporal Coverage"))
        self.label_10.setText(_translate("service_configuration_widget_base", "Starting date"))
        self.label_11.setText(_translate("service_configuration_widget_base", "Ending date"))
        self.groupBox.setTitle(_translate("service_configuration_widget_base", "Basic Information"))
        self.label_22.setText(_translate("service_configuration_widget_base", "Data description URL"))
        self.label_7.setText(_translate("service_configuration_widget_base", "Web Service managed by"))
        self.label.setText(_translate("service_configuration_widget_base", "Title"))
        self.label_8.setText(_translate("service_configuration_widget_base", "Web Service managed by URL"))
        self.label_6.setText(_translate("service_configuration_widget_base", "Data license URL"))
        self.label_4.setText(_translate("service_configuration_widget_base", "Web Service user manual URL"))
        self.label_2.setText(_translate("service_configuration_widget_base", "Web Service description"))
        self.label_23.setText(_translate("service_configuration_widget_base", "List of relevant Publications"))
        self.label_3.setText(_translate("service_configuration_widget_base", "Web Service description URL"))
        self.label_5.setText(_translate("service_configuration_widget_base", "Data license"))
        self.label_21.setText(_translate("service_configuration_widget_base", "Data description"))
        self.group_label.setText(_translate("service_configuration_widget_base", "Service group"))
        self.group_ogc_layers.setTitle(_translate("service_configuration_widget_base", "OGC Layer Configuration"))
        self.group_capabilities.setTitle(_translate("service_configuration_widget_base", "Web Service Capabilities"))
        self.check_radius_of_circular_area_is_specified_in_km.setText(_translate("service_configuration_widget_base", "Radius of circular area can be specified in km"))
        self.check_filter_by_magnitude_type.setText(_translate("service_configuration_widget_base", "Filter by magnitude type"))
        self.check_can_include_arrivals.setText(_translate("service_configuration_widget_base", "Can include arrivals"))
        self.check_filter_data_updated_after.setText(_translate("service_configuration_widget_base", "Filter data updated after"))
        self.check_filter_by_originid.setText(_translate("service_configuration_widget_base", "Filter by OriginID"))
        self.check_can_include_all_origins.setText(_translate("service_configuration_widget_base", "Can include all origins"))
        self.check_filter_by_contributor.setText(_translate("service_configuration_widget_base", "Query Contributors"))
        self.check_can_output_kml.setText(_translate("service_configuration_widget_base", "Can output KML"))
        self.check_filter_by_event_type.setText(_translate("service_configuration_widget_base", "Filter by event type"))
        self.check_filter_by_eventid.setText(_translate("service_configuration_widget_base", "Filter by EventID"))
        self.check_can_output_geojson.setText(_translate("service_configuration_widget_base", "Can output GeoJSON"))
        self.check_can_output_microsoft_xlsx.setText(_translate("service_configuration_widget_base", "Can output Microsoft XLSX"))
        self.check_can_output_text.setText(_translate("service_configuration_widget_base", "Can output text"))
        self.check_filter_by_magnitudeid.setText(_translate("service_configuration_widget_base", "Filter by MagnitudeID"))
        self.check_can_output_xml.setText(_translate("service_configuration_widget_base", "Can output XML"))
        self.check_can_filter_using_circular_area.setText(_translate("service_configuration_widget_base", "Can filter using a circular area"))
        self.check_can_include_all_stations_magnitudes.setText(_translate("service_configuration_widget_base", "Can include all stations magnitudes"))
        self.check_can_include_all_origins_multiple.setText(_translate("service_configuration_widget_base", "Can include all origins for multiple events"))
        self.check_filter_by_catalog.setText(_translate("service_configuration_widget_base", "Filter by Catalog"))
        self.check_filter_by_focalmechanismid.setText(_translate("service_configuration_widget_base", "Filter by FocalMechanismID"))
        self.check_can_filter_by_depth.setText(_translate("service_configuration_widget_base", "Can filter by depth"))
        self.check_can_include_all_magnitudes.setText(_translate("service_configuration_widget_base", "Can include all magnitudes"))
        self.check_has_limit_of_entries.setText(_translate("service_configuration_widget_base", "Has limit of"))
        self.label_17.setText(_translate("service_configuration_widget_base", "entries"))
        self.check_filter_by_contributorid.setText(_translate("service_configuration_widget_base", "Filter by ContributorID"))
        self.check_can_output_json.setText(_translate("service_configuration_widget_base", "Can output JSON"))
        self.check_can_include_all_magnitudes_multiple.setText(_translate("service_configuration_widget_base", "Can include all magnitudes for multiple events"))
        self.check_http_code_nodata.setText(_translate("service_configuration_widget_base", "HTTP code no data"))
        self.group_bounding_box.setTitle(_translate("service_configuration_widget_base", "Web Service Geographical Coverage"))
        self.label_14.setText(_translate("service_configuration_widget_base", "Minimum longitude"))
        self.label_15.setText(_translate("service_configuration_widget_base", "Maximum longitude"))
        self.label_13.setText(_translate("service_configuration_widget_base", "Maximum latitude"))
        self.label_12.setText(_translate("service_configuration_widget_base", "Minimum latitude"))
        self.button_load_service_capabilities.setTitle(_translate("service_configuration_widget_base", "Web Service Basic Information"))
        self.label_9.setText(_translate("service_configuration_widget_base", "Web service URL"))
        self.button_load_service.setText(_translate("service_configuration_widget_base", "Load Web Service Capabilities"))
from qgis.gui import QgsCodeEditor, QgsMessageBar
from qgsdatetimeedit import QgsDateTimeEdit
