# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QQuakeDialog
                                 A QGIS plugin
 QQuake plugin to download seismologic data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-11-20
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Faunalia
        email                : matteo.ghetta@faunalia.eu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import re

from qgis.PyQt import uic
from qgis.PyQt.QtWidgets import QWidget, QFileDialog
from qgis.PyQt.QtCore import pyqtSignal, QDir

from qgis.core import (
    QgsSettings
)

from qquake.gui.gui_utils import GuiUtils
from qquake.gui.output_table_options_dialog import OutputTableOptionsDialog
from qquake.services import SERVICE_MANAGER
from qquake.fetcher import Fetcher

FORM_CLASS, _ = uic.loadUiType(GuiUtils.get_ui_file_path('filter_station_by_id_widget_base.ui'))


class FilterStationByIdWidget(QWidget, FORM_CLASS):
    changed = pyqtSignal()

    def __init__(self, iface, service_type, parent=None):
        """Constructor."""
        super().__init__(parent)

        self.setupUi(self)

        self.radio_network_code.toggled.connect(self._enable_widgets)
        self.radio_station_code.toggled.connect(self._enable_widgets)
        self.radio_location_code.toggled.connect(self._enable_widgets)

        self.radio_basic_output.toggled.connect(self._enable_widgets)
        self.radio_extended_output.toggled.connect(self._enable_widgets)

        self._enable_widgets()

        self.output_table_options_button.clicked.connect(self._output_table_options)

        self.service_type = None
        self.service_id = None
        self.set_service_type(service_type)
        self.output_fields = None

        self.radio_network_code.toggled.connect(self.changed)
        self.edit_network_code.textChanged.connect(self.changed)
        self.radio_station_code.toggled.connect(self.changed)
        self.edit_station_code.textChanged.connect(self.changed)
        self.radio_location_code.toggled.connect(self.changed)
        self.edit_location_code.textChanged.connect(self.changed)
        self.radio_basic_output.toggled.connect(self.changed)
        self.radio_extended_output.toggled.connect(self.changed)

    def set_service_type(self, service_type):
        self.service_type = service_type

    def set_service_id(self, service_id):
        self.service_id = service_id
        if 'fields' in SERVICE_MANAGER.service_details(self.service_type, self.service_id)['default']:
            self.output_fields = SERVICE_MANAGER.service_details(self.service_type, service_id)['default']['fields']

    def restore_settings(self, prefix):
        s = QgsSettings()
        self.edit_network_code.setText(s.value('/plugins/qquake/{}_network_code'.format(prefix), '', str))
        self.edit_station_code.setText(s.value('/plugins/qquake/{}_station_code'.format(prefix), '', str))
        self.edit_location_code.setText(s.value('/plugins/qquake/{}_location_code'.format(prefix), '', str))

        if s.value('/plugins/qquake/{}_network_code_checked'.format(prefix), True, bool):
            self.radio_network_code.setChecked(True)
        if s.value('/plugins/qquake/{}_station_code_checked'.format(prefix), True, bool):
            self.radio_station_code.setChecked(True)
        if s.value('/plugins/qquake/{}_location_code_checked'.format(prefix), True, bool):
            self.radio_location_code.setChecked(True)

        self.radio_basic_output.setChecked(
            s.value('/plugins/qquake/{}_single_event_basic_checked'.format(prefix), True, bool))
        self.radio_extended_output.setChecked(
            s.value('/plugins/qquake/{}_single_event_extended_checked'.format(prefix), False, bool))

    def save_settings(self, prefix):
        s = QgsSettings()
        s.setValue('/plugins/qquake/{}_network_code'.format(prefix), self.edit_network_code.text())
        s.setValue('/plugins/qquake/{}_station_code'.format(prefix), self.edit_station_code.text())
        s.setValue('/plugins/qquake/{}_location_code'.format(prefix), self.edit_location_code.text())

        s.setValue('/plugins/qquake/{}_network_code_checked'.format(prefix), self.radio_network_code.isChecked())
        s.setValue('/plugins/qquake/{}_station_code_checked'.format(prefix), self.radio_station_code.isChecked())
        s.setValue('/plugins/qquake/{}_location_code_checked'.format(prefix), self.radio_location_code.isChecked())

        s.setValue('/plugins/qquake/{}_single_event_basic_checked'.format(prefix), self.radio_basic_output.isChecked())
        s.setValue('/plugins/qquake/{}_single_event_extended_checked'.format(prefix), self.radio_extended_output.isChecked())

    def _enable_widgets(self):
        self.edit_network_code.setEnabled(self.radio_network_code.isChecked())
        self.edit_station_code.setEnabled(self.radio_station_code.isChecked())
        self.edit_location_code.setEnabled(self.radio_location_code.isChecked())

        self.output_table_options_button.setEnabled(self.radio_extended_output.isChecked())

    def _output_table_options(self):
        dlg = OutputTableOptionsDialog(self.service_type, self.service_id, self.output_fields, self)
        if dlg.exec_():
            self.output_fields = dlg.selected_fields()
            self.changed.emit()

    def network_codes(self):
        if self.radio_network_code.isChecked():
            return self.edit_network_code.text().strip()
        else:
            return None

    def station_codes(self):
        if self.radio_station_code.isChecked():
            return self.edit_station_code.text().strip()
        else:
            return None

    def locations(self):
        if self.radio_location_code.isChecked():
            return self.edit_location_code.text().strip()
        else:
            return None

    def output_type(self):
        return Fetcher.BASIC if self.radio_basic_output.isChecked() else Fetcher.EXTENDED