# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QQuakeDialog
                                 A QGIS plugin
 QQuake plugin to download seismologic data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-11-20
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Faunalia
        email                : matteo.ghetta@faunalia.eu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt import uic
from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtWidgets import (
    QDialog,
    QVBoxLayout,
    QDialogButtonBox,
    QListWidgetItem
)

from qgis.gui import QgsGui

from qquake.gui.gui_utils import GuiUtils
from qquake.services import SERVICE_MANAGER

FORM_CLASS, _ = uic.loadUiType(GuiUtils.get_ui_file_path('predefined_areas_widget_base.ui'))


class PredefinedAreasWidget(QDialog, FORM_CLASS):

    def __init__(self, parent=None):
        """Constructor."""
        super().__init__(parent)
        self.setupUi(self)
        self.blocked = False

        for name in SERVICE_MANAGER.available_predefined_bounding_boxes():
            extent = SERVICE_MANAGER.predefined_bounding_box(name)
            item = QListWidgetItem(extent['title'])
            item.setData(Qt.UserRole, name)
            item.setData(Qt.UserRole + 1, extent.get('read_only', False))
            item.setData(Qt.UserRole + 2, extent.get('title', ''))
            item.setData(Qt.UserRole + 3, extent.get('boundingbox', [0, 0, 0, 0])[0])
            item.setData(Qt.UserRole + 4, extent.get('boundingbox', [0, 0, 0, 0])[1])
            item.setData(Qt.UserRole + 5, extent.get('boundingbox', [0, 0, 0, 0])[2])
            item.setData(Qt.UserRole + 6, extent.get('boundingbox', [0, 0, 0, 0])[3])
            self.region_list.addItem(item)

        self.region_list.currentItemChanged.connect(self._item_changed)

        self.button_add.clicked.connect(self._add_item)
        self.button_remove.clicked.connect(self._remove_item)

        self.edit_label.textEdited.connect(self._update_item)
        self.spin_min_long.valueChanged.connect(self._update_item)
        self.spin_max_long.valueChanged.connect(self._update_item)
        self.spin_min_lat.valueChanged.connect(self._update_item)
        self.spin_max_lat.valueChanged.connect(self._update_item)

    def _update_item(self):
        if self.blocked:
            return

        current = self.region_list.currentItem()
        read_only = current.data(Qt.UserRole + 1)
        if read_only:
            return

        self.blocked = True
        current.setData(Qt.UserRole+2, self.edit_label.text())
        current.setText(self.edit_label.text())
        current.setData(Qt.UserRole + 3, self.spin_min_long.value())
        current.setData(Qt.UserRole + 5, self.spin_max_long.value())
        current.setData(Qt.UserRole + 4, self.spin_min_lat.value())
        current.setData(Qt.UserRole + 6, self.spin_max_lat.value())
        self.blocked = False

    def _item_changed(self, current, previous):
        if self.blocked:
            return

        self.blocked = True
        self.edit_label.setText(current.data(Qt.UserRole+2))
        self.spin_min_long.setValue(current.data(Qt.UserRole+3))
        self.spin_max_long.setValue(current.data(Qt.UserRole+5))
        self.spin_min_lat.setValue(current.data(Qt.UserRole+4))
        self.spin_max_lat.setValue(current.data(Qt.UserRole+6))

        read_only = current.data(Qt.UserRole + 1)
        for w in [self.edit_label, self.spin_min_long, self.spin_max_long, self.spin_min_lat, self.spin_max_lat]:
            w.setEnabled(not read_only)
        self.button_remove.setEnabled(not read_only)
        self.blocked = False

    def _add_item(self):
        item = QListWidgetItem('New Area')
        item.setData(Qt.UserRole, None)
        item.setData(Qt.UserRole + 1, False)
        item.setData(Qt.UserRole + 2, 'New Area')
        item.setData(Qt.UserRole + 3, 0)
        item.setData(Qt.UserRole + 4, 0)
        item.setData(Qt.UserRole + 5, 0)
        item.setData(Qt.UserRole + 6, 0)
        self.region_list.addItem(item)
        self.region_list.setCurrentItem(item)

    def _remove_item(self):
        item = self.region_list.currentItem()
        self.region_list.takeItem(self.region_list.row(item))


class PredefinedAreasDialog(QDialog):

    def __init__(self, parent=None):
        """Constructor."""
        super().__init__(parent)

        self.setWindowTitle(self.tr('Customize Areas'))

        QgsGui.enableAutoGeometryRestore(self)

        self.widget = PredefinedAreasWidget()
        l = QVBoxLayout()
        l.addWidget(self.widget)
        self.button_box = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)
        self.button_box.accepted.connect(self.accept)
        self.button_box.rejected.connect(self.reject)
        l.addWidget(self.button_box)
        self.setLayout(l)
