# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QQuakeDialog
                                 A QGIS plugin
 QQuake plugin to download seismologic data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-11-20
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Faunalia
        email                : matteo.ghetta@faunalia.eu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt import uic
from qgis.PyQt.QtWidgets import QWidget

from qquake.services import SERVICE_MANAGER
from qquake.gui.gui_utils import GuiUtils

FORM_CLASS, _ = uic.loadUiType(GuiUtils.get_ui_file_path('service_information_widget.ui'))


class ServiceInformationWidget(QWidget, FORM_CLASS):

    def __init__(self, iface, parent=None):
        """Constructor."""
        super().__init__(parent)
        self.iface = iface
        self.setupUi(self)
        self.info_browser.viewport().setAutoFillBackground(False)

        self.layer_model = None
        self.service_type = None
        self.service_id = None
        self.service_config = None

    def set_service(self, service_id, service_type):
        self.service_type = service_type
        self.service_id = service_id
        self.service_config = SERVICE_MANAGER.service_details(service_type, service_id)

        html = """<p><b>Title</b><br>
        {title}</p>
        <p><b>Description</b><br>
        <a href="{infourl}">{info}</a></p>""".format(**self.service_config)

        if self.service_config.get('help'):
            html += """
            <p><b>Help</b><br>
            <a href="{help}">{help}</a></p>
            """.format(**self.service_config)

        html += """<p><b>Data license</b><br>
            <a href="{datalicenseurl}">{datalicense}</a></p>
            """.format(**self.service_config)

        html += """<p><b>Service managed by</b><br>
            <a href="{dataproviderurl}">{dataprovider}</a></p>
            """.format(**self.service_config)

        capabilities = []

        if service_type in (SERVICE_MANAGER.MACROSEISMIC, SERVICE_MANAGER.FDSNSTATION, SERVICE_MANAGER.FDSNEVENT):
            if self.service_config['settings'].get('querylimitmaxentries'):
                capabilities.append('Maximum entries returned: {}'.format(self.service_config['settings'].get('querylimitmaxentries')))
            if self.service_config.get('datestart'):
                capabilities.append(
                    'Earliest date: {}'.format(self.service_config['datestart']))
            if self.service_config.get('dateend'):
                capabilities.append(
                    'Latest date: {}'.format(self.service_config['dateend']))

        if capabilities:
            html += """<p><b>Capabilities</b>"""
            html += ''.join(['<li>{}</li>'.format(c) for c in capabilities])
            html += """</p>"""

        self.info_browser.setHtml(html)
